common: &common
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 50
  min_messages: warning

development:
  database: mrv_development
  username:
  password:
  <<: *common

test:
  database: mrv_test
  <<: *common

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %> #This is the environment variable created by our Dokku command earlier
  encoding: unicode
  pool: 5
